'use client';

import { useState } from 'react';
import { PursuitBattleCard } from '@/lib/types/pursuit';

interface Props {
  battleCard: PursuitBattleCard;
  preparedBy?: string;
}

function buildMarkdown(card: PursuitBattleCard, preparedBy?: string): string {
  const lines: string[] = [];
  const title = [card.platformName, card.siName].filter(Boolean).join(' + ');
  lines.push(`# Stratwyze Pursuit Battle Card — ${title}`);
  if (preparedBy) lines.push(`**Prepared by:** ${preparedBy}`);
  lines.push('');
  lines.push(`**Opening:** ${card.openingStatement}`);
  lines.push('');

  if (card.platformWeaknesses.length > 0) {
    lines.push(`## Platform Risk — ${card.platformName}`);
    card.platformWeaknesses.forEach((w, i) => lines.push(`${i + 1}. ${w}`));
    lines.push('');
  }

  if (card.siWeaknesses.length > 0) {
    lines.push(`## SI Risk — ${card.siName}`);
    card.siWeaknesses.forEach((w, i) => lines.push(`${i + 1}. ${w}`));
    lines.push('');
  }

  lines.push('## The Winning Play');
  lines.push(card.combinedNarrative);
  if (card.winStatement) lines.push(`\n> ${card.winStatement}`);
  lines.push('');

  lines.push('## Stakeholder Talking Points');
  card.stakeholderAngles.forEach(angle => {
    lines.push(`\n### ${angle.persona} — ${angle.headline}`);
    angle.talkingPoints.forEach(tp => lines.push(`- ${tp}`));
    if (angle.watchOut) lines.push(`\n*Watch: ${angle.watchOut}*`);
  });
  lines.push('');

  if (card.watchOuts.length > 0) {
    lines.push('## Watch Outs');
    card.watchOuts.forEach(w => lines.push(`- ${w}`));
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by Stratwyze CRM · stratwyze.co.za*`);

  return lines.join('\n');
}

export default function BattleCardExport({ battleCard, preparedBy }: Props) {
  const [copied, setCopied] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = async () => {
    const md = buildMarkdown(battleCard, preparedBy);
    try {
      await navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = md;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleCopy}
        className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-xs font-semibold transition-all"
      >
        {copied ? (
          <>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-green-600">
              <polyline points="20 6 9 17 4 12" />
            </svg>
            <span className="text-green-600">Copied</span>
          </>
        ) : (
          <>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
            </svg>
            Copy as Markdown
          </>
        )}
      </button>

      <button
        onClick={handlePrint}
        className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold transition-all shadow-sm"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <polyline points="6 9 6 2 18 2 18 9" />
          <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
          <rect x="6" y="14" width="12" height="8" />
        </svg>
        Export Brief
      </button>
    </div>
  );
}
