'use client';

import { useState } from 'react';
import { Competitor, RiskLevel } from '@/lib/types/competitive';
import { computeBattleCard } from '@/lib/utils/battle-card';
import { toast } from '@/lib/toast';

const RISK_BADGE_COLORS: Record<RiskLevel, string> = {
  Critical: 'bg-red-100 text-red-700 border border-red-300',
  High: 'bg-orange-100 text-orange-700 border border-orange-300',
  Medium: 'bg-blue-100 text-blue-700 border border-blue-300',
  Low: 'bg-green-100 text-green-700 border border-green-300',
};

const AVATAR_COLORS: Record<RiskLevel, string> = {
  Critical: 'bg-red-500',
  High: 'bg-orange-500',
  Medium: 'bg-blue-500',
  Low: 'bg-green-500',
};

interface CompetitorDetailPanelProps {
  competitor: Competitor | null;
  dealTitle?: string;
}

function buildProposalMarkdown(competitor: Competitor, dealTitle?: string): string {
  const card = computeBattleCard(competitor, null);
  const lines: string[] = [];

  lines.push(`## Competitive Intelligence — ${competitor.name}`);
  if (dealTitle) lines.push(`*Deal: ${dealTitle}*`);
  lines.push('');
  lines.push(`**Risk Level:** ${competitor.riskLevel}`);
  lines.push(`**Revenue:** ${competitor.revenue}  |  **Deployment:** ${competitor.deployment}`);
  lines.push('');
  lines.push(`### Why HaloITSM Wins`);
  lines.push(card.combinedNarrative);
  lines.push('');
  lines.push(`### Key Weaknesses to Exploit`);
  competitor.keyWeaknesses.forEach((w, i) => {
    lines.push(`${i + 1}. **${w.title}** — ${w.description}`);
  });
  lines.push('');
  lines.push(`### TCO Comparison (3-Year)`);
  lines.push(`- ${competitor.name}: R${competitor.tco3Year.competitor.min / 1000}–${competitor.tco3Year.competitor.max / 1000}M`);
  lines.push(`- HaloITSM: R${competitor.tco3Year.haloITSM.min / 1000}–${competitor.tco3Year.haloITSM.max / 1000}M`);
  lines.push('');
  lines.push(`### Sales Rebuttal`);
  lines.push(competitor.salesRebuttal.keyMessage);
  lines.push('');
  lines.push(`---`);
  lines.push(`*Generated by Stratwyze CRM*`);

  return lines.join('\n');
}

export default function CompetitorDetailPanel({ competitor, dealTitle }: CompetitorDetailPanelProps) {
  const [showFullCard, setShowFullCard] = useState(false);
  const [injecting, setInjecting] = useState(false);

  if (!competitor) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs flex items-center justify-center h-96">
        <div className="text-center">
          <div className="w-12 h-12 rounded-xl bg-slate-100 flex items-center justify-center mx-auto mb-4">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-slate-400">
              <circle cx="12" cy="12" r="1" />
              <path d="M4 12a8 8 0 0 1 16 0M2 12a10 10 0 0 1 20 0" />
            </svg>
          </div>
          <p className="text-slate-600 text-sm">Select a competitor</p>
          <p className="text-slate-500 text-xs mt-1">Click any card to open the full sales battle card & rebuttals</p>
        </div>
      </div>
    );
  }

  const badgeColor = RISK_BADGE_COLORS[competitor.riskLevel];
  const avatarColor = AVATAR_COLORS[competitor.riskLevel];

  const handleInjectToProposal = async () => {
    setInjecting(true);
    try {
      const md = buildProposalMarkdown(competitor, dealTitle);
      await navigator.clipboard.writeText(md);
      toast('Battle card copied — paste into your proposal doc', 'success');
    } catch {
      toast('Failed to copy to clipboard', 'error');
    } finally {
      setInjecting(false);
    }
  };

  return (
    <>
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        {/* Header */}
        <div className={`p-6 bg-gradient-to-r ${
          competitor.riskLevel === 'Critical' ? 'from-red-50 to-red-100' :
          competitor.riskLevel === 'High' ? 'from-orange-50 to-orange-100' :
          competitor.riskLevel === 'Medium' ? 'from-blue-50 to-blue-100' :
          'from-green-50 to-green-100'
        }`}>
          <div className="flex items-start gap-4 mb-4">
            <div className={`w-12 h-12 rounded-lg ${avatarColor} flex items-center justify-center text-white font-bold`}>
              {competitor.avatar}
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="text-lg font-bold text-slate-900">{competitor.name}</h3>
              <p className="text-sm text-slate-600">{competitor.ownership}</p>
            </div>
            <span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${badgeColor} flex-shrink-0`}>
              {competitor.riskLevel} Risk
            </span>
          </div>
        </div>

        {/* Metrics Grid */}
        <div className="grid grid-cols-2 gap-4 p-6 border-b border-slate-200">
          <div>
            <p className="text-xs font-semibold uppercase text-slate-500 mb-1">Revenue</p>
            <p className="text-base font-bold text-slate-900">{competitor.revenue}</p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase text-slate-500 mb-1">Deployment</p>
            <p className="text-base font-bold text-slate-900">{competitor.deployment}</p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase text-slate-500 mb-1">Their 3YR TCO</p>
            <p className="text-sm font-bold text-slate-900">
              R{competitor.tco3Year.competitor.min / 1000}–{competitor.tco3Year.competitor.max / 1000}M
            </p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase text-slate-500 mb-1">HaloITSM TCO</p>
            <p className="text-sm font-bold text-blue-600">
              R{competitor.tco3Year.haloITSM.min / 1000}–{competitor.tco3Year.haloITSM.max / 1000}M
            </p>
          </div>
        </div>

        {/* Key Weaknesses */}
        <div className="p-6 border-b border-slate-200">
          <h4 className="text-sm font-bold text-slate-900 mb-4">Key Weaknesses to Exploit</h4>
          <div className="space-y-3">
            {competitor.keyWeaknesses.map((weakness, i) => (
              <div key={i} className="flex gap-3">
                <div className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 text-white text-xs font-bold ${
                  competitor.riskLevel === 'Critical' ? 'bg-red-500' :
                  competitor.riskLevel === 'High' ? 'bg-orange-500' : 'bg-blue-500'
                }`}>
                  {i + 1}
                </div>
                <div>
                  <p className="text-sm font-semibold text-slate-900">{weakness.title}</p>
                  <p className="text-xs text-slate-600 mt-0.5">{weakness.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Sales Rebuttal */}
        <div className="p-6 bg-blue-50 border-b border-blue-200">
          <div className="flex items-start gap-2 mb-2">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-blue-600 mt-0.5 flex-shrink-0">
              <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
            <h4 className="text-sm font-bold text-blue-900">Sales Rebuttal & Pitch</h4>
          </div>
          <p className="text-sm text-blue-800 leading-snug">{competitor.salesRebuttal.keyMessage}</p>
        </div>

        {/* Action Buttons */}
        <div className="p-6 flex gap-3">
          <button
            onClick={() => setShowFullCard(true)}
            className="flex-1 px-4 py-2.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold transition-all shadow-sm flex items-center justify-center gap-2"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
            </svg>
            Full Battle Card
          </button>
          <button
            onClick={handleInjectToProposal}
            disabled={injecting}
            className="flex-1 px-4 py-2.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-900 text-sm font-semibold transition-all border border-slate-300 disabled:opacity-50"
          >
            {injecting ? 'Copying…' : 'Inject to Proposal'}
          </button>
        </div>
      </div>

      {/* Full Battle Card Modal */}
      {showFullCard && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-start justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl my-8">
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
              <div className="flex items-center gap-3">
                <div className={`w-9 h-9 rounded-lg ${avatarColor} flex items-center justify-center text-white font-bold text-sm`}>
                  {competitor.avatar}
                </div>
                <div>
                  <h2 className="text-base font-bold text-slate-900">{competitor.name} — Full Battle Card</h2>
                  <p className="text-xs text-slate-500">{competitor.ownership}</p>
                </div>
              </div>
              <button
                onClick={() => setShowFullCard(false)}
                className="w-8 h-8 rounded-lg hover:bg-slate-100 flex items-center justify-center text-slate-500 transition-colors"
              >
                ✕
              </button>
            </div>

            <div className="p-6 space-y-6">
              {/* Summary metrics */}
              <div className="grid grid-cols-2 gap-3">
                {[
                  { label: 'Revenue', value: competitor.revenue },
                  { label: 'Deployment', value: competitor.deployment },
                  { label: `${competitor.name} 3YR TCO`, value: `R${competitor.tco3Year.competitor.min/1000}–${competitor.tco3Year.competitor.max/1000}M`, color: 'text-red-600' },
                  { label: 'HaloITSM 3YR TCO', value: `R${competitor.tco3Year.haloITSM.min/1000}–${competitor.tco3Year.haloITSM.max/1000}M`, color: 'text-blue-600' },
                ].map(({ label, value, color }) => (
                  <div key={label} className="bg-slate-50 rounded-lg p-3">
                    <p className="text-xs text-slate-500 mb-1">{label}</p>
                    <p className={`text-sm font-bold ${color || 'text-slate-900'}`}>{value}</p>
                  </div>
                ))}
              </div>

              {/* All weaknesses */}
              <div>
                <h3 className="text-sm font-bold text-slate-900 mb-3">Key Weaknesses to Exploit</h3>
                <div className="space-y-3">
                  {competitor.keyWeaknesses.map((w, i) => (
                    <div key={i} className={`p-3 rounded-lg border-l-4 ${
                      competitor.riskLevel === 'Critical' ? 'border-red-400 bg-red-50' :
                      competitor.riskLevel === 'High' ? 'border-orange-400 bg-orange-50' : 'border-blue-400 bg-blue-50'
                    }`}>
                      <p className="text-sm font-semibold text-slate-900">{w.title}</p>
                      <p className="text-xs text-slate-700 mt-1">{w.description}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Functionality gaps */}
              {competitor.functionality && competitor.functionality.length > 0 && (
                <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-3">Functionality Gaps</h3>
                  <div className="space-y-2">
                    {competitor.functionality.map((gap, i) => (
                      <div key={i} className="flex gap-3 text-sm p-3 bg-slate-50 rounded-lg">
                        <span className={`px-2 py-0.5 text-xs font-semibold rounded self-start flex-shrink-0 ${
                          gap.severity === 'Critical' ? 'bg-red-100 text-red-700' :
                          gap.severity === 'High' ? 'bg-orange-100 text-orange-700' : 'bg-amber-100 text-amber-700'
                        }`}>{gap.severity}</span>
                        <div className="min-w-0">
                          <p className="font-medium text-slate-900">{gap.category}</p>
                          <p className="text-xs text-slate-600 mt-0.5">{gap.gap}</p>
                          <p className="text-xs text-emerald-700 mt-1">✓ {gap.halITSMAdvantage}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Win statement */}
              <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4">
                <p className="text-xs font-semibold text-emerald-700 mb-2 uppercase tracking-wide">Winning Pitch</p>
                <p className="text-sm text-emerald-900 font-medium">{competitor.salesRebuttal.keyMessage}</p>
              </div>

              {/* Rebuttal points */}
              {competitor.salesRebuttal.winningPoints && competitor.salesRebuttal.winningPoints.length > 0 && (
                <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-3">Winning Points</h3>
                  <ul className="space-y-2">
                    {competitor.salesRebuttal.winningPoints.map((pt, i) => (
                      <li key={i} className="flex gap-2 text-sm text-slate-700">
                        <span className="text-emerald-500 font-bold flex-shrink-0">✓</span>
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-4 border-t border-slate-200 flex gap-3">
              <button
                onClick={handleInjectToProposal}
                disabled={injecting}
                className="flex-1 px-4 py-2.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold transition-all disabled:opacity-50"
              >
                {injecting ? 'Copying…' : '📋 Copy to Proposal'}
              </button>
              <button
                onClick={() => setShowFullCard(false)}
                className="px-4 py-2.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-sm font-semibold transition-all"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
